# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md

version: '3.7'
services:

  database:
    image: webpwnized/mutillidae:database
    build: 
        context: ./database
        dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password

  database_admin:
    depends_on:
    - database
    image: webpwnized/mutillidae:database_admin
    build:
        context: ./database_admin
        dockerfile: Dockerfile
    ports:
    - 127.0.0.1:81:80

  www:
    depends_on:
    - database
    - ldap
    image: webpwnized/mutillidae:www
    build:
        context: ./www
        dockerfile: Dockerfile
    volumes:
    # Make the Apache log files on the image available to localhost
    - "./www/var-log-apache2/:/var/log/apache2/"
    ports:
    - 127.0.0.1:80:80
    - 127.0.0.1:443:443

  ldap:
    image: webpwnized/mutillidae:ldap
    build:
        context: ./ldap
        dockerfile: Dockerfile
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  ldap_admin:
    depends_on:
    - ldap
    image: webpwnized/mutillidae:ldap_admin
    build:
        context: ./ldap_admin          
        dockerfile: Dockerfile
    ports:
    - 127.0.0.1:82:80
   
volumes:
  ldap_data:
  ldap_config:
