name: build-push-dockerhub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get version from version file
        run: |
          VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push database container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: webpwnized/mutillidae:database
      -
        name: Build and push database container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: webpwnized/mutillidae:database-${{ env.VERSION }}




